version: '3'

services:
  scraper:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports:
      - "6379:6379"

    depends_on:
      - scraper
