version: '3'

services:
  scraper:
    build: .
    ports:
      - "5000:5000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports:
      - "6379:6379"
    depends_on:
      - scraper
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - scraper
